dependencies:
 CrimsonHttp:
  git: git://github.com/zhygr/CrimsonHttp.git
 log4dart:
  git: git://github.com/zhygr/log4dart.git
 MustacheDartPort:
  git: git://github.com/zhygr/MustacheDartPort.git
 edt:
  git: https://github.com/zhygr/edt.git
 mongo-dart:
  git: https://github.com/zhygr/mongo-dart.git